# pins for basashi
[shorturls]
gh = "github:{path}"
me = "github:seallegg/{path}"
ms = "github:manic-systems/{path}"

# opt out with exclude_follow
[all_follow]
nixpkgs = ["nixpkgs", "nixpkgs-darwin"]
hjem = "hjem"

[inputs]
# core
nixpkgs.url = "gh:NixOS/nixpkgs/nixos-unstable"
hjem.url = "gh:feel-co/hjem"
hjem-rum.url = "gh:snugnug/hjem-rum"
disko.url = "gh:nix-community/disko"
nix-secrets.url = "gh:unnamed-systems/nix-secrets"

# manic systems
tack.url = "ms:tack"
nixos-core.url = "ms:nixos-core"

# mine
apple-fonts.url = "me:apple-fonts-flake"
qt6ct-kde.url = "me:qt6ct-kde-flake"

# others
helium.url = "gh:schembriaiden/helium-browser-nix-flake"
nixdg-ninja.url = "gh:NotAShelf/nixdg-ninja"
openlogi.url = "gh:AprilNEA/OpenLogi"
cachyos-kernel = { url = "gh:xddxdd/nix-cachyos-kernel", exclude_follow = ["nixpkgs"] }
